/**
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributesValueStruct from './AttributesValueStruct';

/**
 * The AttributesValues model module.
 * @module model/AttributesValues
 * @version 3.0.0
 */
class AttributesValues {
    /**
     * Constructs a new <code>AttributesValues</code>.
     * @alias module:model/AttributesValues
     */
    constructor() { 
        
        AttributesValues.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AttributesValues</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AttributesValues} obj Optional instance to populate.
     * @return {module:model/AttributesValues} The populated <code>AttributesValues</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AttributesValues();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('struct')) {
                obj['struct'] = AttributesValueStruct.constructFromObject(data['struct']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
AttributesValues.prototype['id'] = undefined;

/**
 * @member {String} name
 */
AttributesValues.prototype['name'] = undefined;

/**
 * @member {module:model/AttributesValueStruct} struct
 */
AttributesValues.prototype['struct'] = undefined;






export default AttributesValues;

