/**
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VariationsAttributeCombinations model module.
 * @module model/VariationsAttributeCombinations
 * @version 3.0.0
 */
class VariationsAttributeCombinations {
    /**
     * Constructs a new <code>VariationsAttributeCombinations</code>.
     * @alias module:model/VariationsAttributeCombinations
     */
    constructor() { 
        
        VariationsAttributeCombinations.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VariationsAttributeCombinations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VariationsAttributeCombinations} obj Optional instance to populate.
     * @return {module:model/VariationsAttributeCombinations} The populated <code>VariationsAttributeCombinations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VariationsAttributeCombinations();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value_id')) {
                obj['value_id'] = ApiClient.convertToType(data['value_id'], 'String');
            }
            if (data.hasOwnProperty('value_name')) {
                obj['value_name'] = ApiClient.convertToType(data['value_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
VariationsAttributeCombinations.prototype['name'] = undefined;

/**
 * @member {String} value_id
 */
VariationsAttributeCombinations.prototype['value_id'] = undefined;

/**
 * @member {String} value_name
 */
VariationsAttributeCombinations.prototype['value_name'] = undefined;






export default VariationsAttributeCombinations;

