/**
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VariationsAttributeCombinations from './VariationsAttributeCombinations';

/**
 * The Variations model module.
 * @module model/Variations
 * @version 3.0.0
 */
class Variations {
    /**
     * Constructs a new <code>Variations</code>.
     * @alias module:model/Variations
     */
    constructor() { 
        
        Variations.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Variations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Variations} obj Optional instance to populate.
     * @return {module:model/Variations} The populated <code>Variations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Variations();

            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('attribute_combinations')) {
                obj['attribute_combinations'] = ApiClient.convertToType(data['attribute_combinations'], [VariationsAttributeCombinations]);
            }
            if (data.hasOwnProperty('available_quantity')) {
                obj['available_quantity'] = ApiClient.convertToType(data['available_quantity'], 'Number');
            }
            if (data.hasOwnProperty('sold_quantity')) {
                obj['sold_quantity'] = ApiClient.convertToType(data['sold_quantity'], 'Number');
            }
            if (data.hasOwnProperty('picture_ids')) {
                obj['picture_ids'] = ApiClient.convertToType(data['picture_ids'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} price
 */
Variations.prototype['price'] = undefined;

/**
 * @member {Array.<module:model/VariationsAttributeCombinations>} attribute_combinations
 */
Variations.prototype['attribute_combinations'] = undefined;

/**
 * @member {Number} available_quantity
 */
Variations.prototype['available_quantity'] = undefined;

/**
 * @member {Number} sold_quantity
 */
Variations.prototype['sold_quantity'] = undefined;

/**
 * @member {Array.<String>} picture_ids
 */
Variations.prototype['picture_ids'] = undefined;






export default Variations;

