/**
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* ItemsHealth service.
* @module meli-marketplace-lib/ItemsHealthApi
* @version 3.0.0
*/
export default class ItemsHealthApi {

    /**
    * Constructs a new ItemsHealthApi. 
    * @alias module:meli-marketplace-lib/ItemsHealthApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the itemsIdHealthActionsGet operation.
     * @callback module:meli-marketplace-lib/ItemsHealthApi~itemsIdHealthActionsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return item health actions by id.
     * @param {String} id 
     * @param {String} accessToken 
     * @param {module:meli-marketplace-lib/ItemsHealthApi~itemsIdHealthActionsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    itemsIdHealthActionsGet(id, accessToken, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling itemsIdHealthActionsGet");
      }
      // verify the required parameter 'accessToken' is set
      if (accessToken === undefined || accessToken === null) {
        throw new Error("Missing the required parameter 'accessToken' when calling itemsIdHealthActionsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'access_token': accessToken
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/items/{id}/health/actions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the itemsIdHealthGet operation.
     * @callback module:meli-marketplace-lib/ItemsHealthApi~itemsIdHealthGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return health by id.
     * @param {String} id 
     * @param {String} accessToken 
     * @param {module:meli-marketplace-lib/ItemsHealthApi~itemsIdHealthGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    itemsIdHealthGet(id, accessToken, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling itemsIdHealthGet");
      }
      // verify the required parameter 'accessToken' is set
      if (accessToken === undefined || accessToken === null) {
        throw new Error("Missing the required parameter 'accessToken' when calling itemsIdHealthGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'access_token': accessToken
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/items/{id}/health', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the sitesSiteIdHealthLevelsGet operation.
     * @callback module:meli-marketplace-lib/ItemsHealthApi~sitesSiteIdHealthLevelsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return health levels.
     * @param {String} siteId 
     * @param {module:meli-marketplace-lib/ItemsHealthApi~sitesSiteIdHealthLevelsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    sitesSiteIdHealthLevelsGet(siteId, callback) {
      let postBody = null;
      // verify the required parameter 'siteId' is set
      if (siteId === undefined || siteId === null) {
        throw new Error("Missing the required parameter 'siteId' when calling sitesSiteIdHealthLevelsGet");
      }

      let pathParams = {
        'site_id': siteId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/sites/{site_id}/health_levels', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
