/**
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Attributes from './model/Attributes';
import AttributesValueStruct from './model/AttributesValueStruct';
import AttributesValues from './model/AttributesValues';
import InlineObject from './model/InlineObject';
import Item from './model/Item';
import ItemPictures from './model/ItemPictures';
import Variations from './model/Variations';
import VariationsAttributeCombinations from './model/VariationsAttributeCombinations';
import CategoriesApi from './meli-marketplace-lib/CategoriesApi';
import ItemsApi from './meli-marketplace-lib/ItemsApi';
import ItemsHealthApi from './meli-marketplace-lib/ItemsHealthApi';
import OAuth20Api from './meli-marketplace-lib/OAuth20Api';
import RestClientApi from './meli-marketplace-lib/RestClientApi';


/**
* This is the official NodeJS SDK for the MercadoLibre Marketplace platform..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var meli = require('index'); // See note below*.
* var xxxSvc = new meli.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new meli.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new meli.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new meli.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 3.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Attributes model constructor.
     * @property {module:model/Attributes}
     */
    Attributes,

    /**
     * The AttributesValueStruct model constructor.
     * @property {module:model/AttributesValueStruct}
     */
    AttributesValueStruct,

    /**
     * The AttributesValues model constructor.
     * @property {module:model/AttributesValues}
     */
    AttributesValues,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The Item model constructor.
     * @property {module:model/Item}
     */
    Item,

    /**
     * The ItemPictures model constructor.
     * @property {module:model/ItemPictures}
     */
    ItemPictures,

    /**
     * The Variations model constructor.
     * @property {module:model/Variations}
     */
    Variations,

    /**
     * The VariationsAttributeCombinations model constructor.
     * @property {module:model/VariationsAttributeCombinations}
     */
    VariationsAttributeCombinations,

    /**
    * The CategoriesApi service constructor.
    * @property {module:meli-marketplace-lib/CategoriesApi}
    */
    CategoriesApi,

    /**
    * The ItemsApi service constructor.
    * @property {module:meli-marketplace-lib/ItemsApi}
    */
    ItemsApi,

    /**
    * The ItemsHealthApi service constructor.
    * @property {module:meli-marketplace-lib/ItemsHealthApi}
    */
    ItemsHealthApi,

    /**
    * The OAuth20Api service constructor.
    * @property {module:meli-marketplace-lib/OAuth20Api}
    */
    OAuth20Api,

    /**
    * The RestClientApi service constructor.
    * @property {module:meli-marketplace-lib/RestClientApi}
    */
    RestClientApi
};
